### ISSUE TITLE
a couple of more instructions

### ISSUE THREAD

**Issue by vajonam** [MichaelB2018/dchs160-mqtt-bridge#2]
can you add which python version you are running this with? I tried 3.6 and 3.7

**Comment by MichaelB2018** [comment]
Python 3.5.3

Do you have any problems with other versions? TBH, I didn't test it on other versions, but neither would have expected issues.

**Comment by vajonam** [comment]
Seemed to work with 3.6.9, but I reverted back to 3.5.3

Also created a Dockerfile to run this from a docker container.

```
FROM python:3.5.3

WORKDIR /usr/src/app

COPY dchs160-mqtt-bridge-master/dchs160-mqtt-bridge.py ./
COPY dchs160-mqtt-bridge-master/defaultConfig.conf ./
COPY run.sh  ./
RUN pip install --no-cache-dir paho-mqtt tendo requests aiohttp xmltodict

ENTRYPOINT [ "./run.sh" ]

```
also a run.sh

```
#!/bin/bash

python dchs160-mqtt-bridge.py -c defaultConfig.conf &
sleep 5s;

tail -F /dchs160-mqtt-bridge.log

```

if you give an option to output the log to stdout (I tired ln -sf /dev/stdout to the log file) it will help with docker running of this daemon.

**Comment by MichaelB2018** [comment]
I believe line 366 would look like logger.addHandler(logging.StreamHandler()) and obviously this would be based on a config parameter. If you  want, you can send me a pull request and I'll incorporate.
