### ISSUE TITLE
Raspbian Buster - dchs160-mqtt-bridge.py - NameError: name 'copyfile' is not defined

### ISSUE THREAD

**Issue by Kryoh-hash** [MichaelB2018/dchs160-mqtt-bridge#3]
Hello !

Im trying to run the dchs160-mqtt-bridge.py on my RaspberryPi 4 in Buster with Python 2.7.16 & 3.7.7, ive tried to run from Python & Python3 and i get this error:

`Traceback (most recent call last):
  File "./dchs160-mqtt-bridge.py", line 401, in <module>
    copyfile(defaultConfigFile, conf_file)
NameError: name 'copyfile' is not defined
`
Installed versions of Python on Rasbpian Buster 10:

`Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2

Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
`
I have checked permissions on the files, and re-checked my config file, cant get it why it fails :/

**Comment by MichaelB2018** [comment]
Can you add in line 26: 

`from shutil import copyfile` 

and let me know if it works.

**Comment by Kryoh-hash** [comment]
It worked flawlessly ! Thanks !  

https://imgur.com/Z0SIqs1
